// Company List
export const RECRUIT_GET_LIST = 'RECRUIT_GET_LIST';
export const RECRUIT_UPDATE_LIST = 'RECRUIT_UPDATE_LIST';
export const RECRUIT_REMOVE_LIST_ID = 'RECRUIT_REMOVE_LIST_ID';
export const RECRUIT_RESET_NEW_ITEM = 'RECRUIT_RESET_NEW_ITEM';
export const RECRUIT_SET_ACTIVE_ID = 'RECRUIT_SET_ACTIVE_ID';
export const RECRUIT_SHOW_NEW_ITEM = 'RECRUIT_SHOW_NEW_ITEM';
